trigger:
- main

schedules:
- cron: "30 6 * * *"
  displayName: "Daily 12:00 PM IST Run"
  branches:
    include:
      - main
  always: true

variables:
- group: new_group

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    python -m pip install --upgrade pip
    pip install dbt-core==1.12.0 dbt-databricks==1.10.9
  displayName: Install dbt

- script: |
    mkdir -p ~/.dbt

    cat <<EOF > ~/.dbt/profiles.yml
    nikitha_dbt_project:
      target: dev
      outputs:
        dev:
          type: databricks
          catalog: $(DBT_CATALOG)
          schema: $(DBT_SCHEMA)
          host: $(DATABRICKS_HOST)
          http_path: $(DATABRICKS_HTTP_PATH)
          token: $(DATABRICKS_TOKEN)
          threads: 1
    EOF
  displayName: Create profiles.yml

- script: dbt debug
  displayName: Test Connection

- script: dbt deps
  displayName: Install Packages

- script: dbt build
  displayName: Run Incremental Models
  